### ISSUE TITLE
Crash de la V3 & V5 

### ISSUE THREAD

**Issue by vincentcau** [eig-2017/parcoursdesoins#2]
Tres bon travail mais j'ai un crash sur la V3 et la V5, normal ?

**Comment by scossin** [comment]
Désolé de répondre si tard. 
La V3 est une appli RShiny standalone, ce n'est pas normal qu'elle crash. Il faudrait ouvrir une issue avec l'erreur de ce crash. 
Pour la V5, c'est normal : il faut commencer par décrire le schéma de la base de données avec des ontologies, puis la charger, dockeriser (Blazegraph et la servlet) avant de lancer RShiny. Le post décrivant l'installation de la V5 est est récent (30 novembre) : http://www.eigsante2017.fr/rapports/rapport8.html . 
Vous pouvez tester les 5 prototypes sans les installer sur le site : http://www.eigsante2017.fr
